version: '3'

services:
  app-1:
    image: "growimulti_app:latest"
    ports:
      - 3001:3000
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://$IP_ADDRESS:27017/growi-1
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi-1
      - PASSWORD_SEED=changeme
    entrypoint: "dockerize
              -wait tcp://$IP_ADDRESS:27017
              -wait tcp://elasticsearch:9200
              -timeout 60s
              /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]
    restart: unless-stopped
    volumes:
      - growi_data_1:/data

  app-2:
    image: "growimulti_app:latest"
    ports:
      - 3002:3000
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://$IP_ADDRESS:27017:27017/growi-2
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi-2
      - PASSWORD_SEED=changeme
    entrypoint: "dockerize
              -wait tcp://$IP_ADDRESS:27017:27017
              -wait tcp://elasticsearch:9200
              -timeout 60s
              /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]
    restart: unless-stopped
    volumes:
      - growi_data_2:/data

  app-3:
    image: "growimulti_app:latest"
    ports:
      - 3003:3000
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://$IP_ADDRESS:27017:27017/growi-3
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi-3
      - PASSWORD_SEED=changeme
    entrypoint: "dockerize
              -wait tcp://$IP_ADDRESS:27017:27017
              -wait tcp://elasticsearch:9200
              -timeout 60s
              /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]
    restart: unless-stopped
    volumes:
      - growi_data_3:/data

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  growi_data_1:
  growi_data_2:
  growi_data_3:
  es_data:
